version: '3.7'

services:
  ngnix-app:
    image: ngnix:1.21.1
    container_name: telzir-ngnix
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./server:/etc/ngnix/conf.d/
      - ./:/var/www/html
    networks:
      - network-telzir
    depends_on:
      - mysql-app

  php:
    build:
      dockerfile: ./php.dockerfile
      context: .
    image: php7.4-fpm
    container_name: telzir-php
    volumes:
      - ./:/var/www/projects
    ports:
      - "9000:9000"
    networks:
      - network-telzir

  mysql-app:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: telzir_database
      MYSQL_ROOT_PASSWORD: laravel
    networks:
      - network-telzir


networks:
  network-telzir:
    driver: bridge
